# Context

## Understanding the data
This data is quite messy. Given that this is spam classification over other tasks like say topic classification, we need to adjust our approach accordingly. When we see odd punctuation, misspelled words, erratic patterns, odd capitializations, these are usually features and not noise.

We also have a dataset of size 5572, this is rather small for advanced methods like Deep Learning, and we **might** result in an overfit model. Because of this, I will spend my time on more traditional methods, but I will look into it if I have time.

## Goal
The [paper](http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/doceng11.pdf) that comes with the dataset, boasts 

| Classifier          | SC%    | BH%  | Acc%   | MCC   |
|---------------------|--------|------|--------|-------|
| SVM + tok1          | 83.10  | 0.18 | 97.64  | 0.893 |
| Boosted NB + tok2   | 84.48  | 0.53 | 97.50  | 0.887 |
| Boosted C4.5 + tok2 | 82.91  | 0.29 | 97.50  | 0.887 |

## Data Status
By the time the data gets to this notebook, it has:
* Been downloaded, and unzipped
* Read into a pandas dataframe

# Approach
There are a few factors at play here and we want to optimize each step.


In [1]:
% matplotlib inline
import pandas as pd
from pathlib import Path
import sys
import seaborn as sns
import re
from pprint import pprint
from itertools import zip_longest
import numpy as np

project_dir = Path.cwd().parent
sys.path.append(str(project_dir/'src'))

# These are utilities that I created to reduce notebook clutter
from make_dataframe import make_dataframe, master_data_handler
import utilities as ut

## Data Acquisition
First we get our data, and then we encode it for use with our Classifiers. We should note our mapping for later on.

In [2]:
master_data_handler()
df = make_dataframe()
df.label = df.label.map({'ham': 0, 'spam': 1})
df.head()

label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

Its interesting to note that, with no machine learning we can get 86.6% Accuracy! This is a good warning that accuracy will probably not be a good metric for us. It also tells us that we have an imbalanced dataset. Depending on our classifier we need to handle this accordingly. 

SVM has a [class_weight parameter](http://scikit-learn.org/stable/auto_examples/svm/plot_separating_hyperplane_unbalanced.html#sphx-glr-auto-examples-svm-plot-separating-hyperplane-unbalanced-py) that allows us to compensate.

Naive Bayes has a [complement class](http://people.csail.mit.edu/jrennie/papers/icml03-nb.pdf) structure that allows us to compensate. It has a corresponding function in sklearn - [ComplementNB](http://scikit-learn.org/dev/modules/generated/sklearn.naive_bayes.ComplementNB.html)

In [3]:
ratio = sum(df.label == 0)/len(df.label)
print('Ratio of ham to total: ', ratio)

Ratio of ham to total:  0.8659368269921034


## Tokenization
As said before, we need to choose a tokenizer that will capture the features we want: 

* Punctuation preservation
* Case preservation
* Full words in tokens

There is research in spam classification [section 3.2](http://www.siefkes.net/ie/winnow-spam.pdf) with some good options. Unfortunately these are all in PCRE regex which python does not support fully (`\p{Z}` among other atoms). But luckily they aren't too hard to convert, given our dataset (minimal control characters). 

I chose the simplified CRM114. Look how it handles an elipsis, we capture an extra feature of `'..'`!

In [4]:
fmt = '%-8s%-20s%s'

print(fmt % ('', 'SCRM114', 'Eager Token'))
for i, (scrm, ets) in enumerate(zip_longest(ut.scrm114_tokenizer(df.text[0]), ut.eager_split_tokenizer(df.text[0]), fillvalue='NULL')):
    print(fmt % (i, scrm, ets))

        SCRM114             Eager Token
0       Go                  Go
1       until               until
2       jurong              jurong
3       point,              point
4       crazy.              
5       .                   crazy
6       Available           
7       only                
8       in                  Available
9       bugis               only
10      n                   in
11      great               bugis
12      world               n
13      la                  great
14      e                   world
15      buffet.             la
16      ..                  e
17      Cine                buffet
18      there               
19      got                 
20      amore               
21      wat.                Cine
22      ..                  there
23      NULL                got
24      NULL                amore
25      NULL                wat
26      NULL                
27      NULL                
28      NULL                


# Modeling

## Classification comparison metric
As suggested in the dataset paper, Matthews Correlation Coefficient has been [researched](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5456046/) to be a metric that is good for unbalanced data.

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef, make_scorer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.text, df.label, test_size=0.65, random_state=0)
data_args = [X_train, y_train, X_test, y_test]

# SVM Training
Optimal linear kernal training [reference](https://www.svm-tutorial.com/2014/10/svm-linear-kernel-good-text-classification/).

In [7]:
pipeline_svm = Pipeline([
    ('vect', CountVectorizer()),
#     ('clf', SVC(kernel='linear')),
    ('clf', LinearSVC()),
])

parameters_svm = {
    'clf__class_weight': [{0: .09}],
    'vect__ngram_range': [(1,1), (1,2), (1,3)],
    'vect__tokenizer': [ut.scrm114_tokenizer, ut.eager_split_tokenizer],
}

ut.grid_search_analysis(pipeline_svm, parameters_svm, *data_args)

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Best score:  0.9165769633559867
Best params:  {'clf__class_weight': {0: 0.09}, 'vect__ngram_range': (1, 1), 'vect__tokenizer': <function eager_split_tokenizer at 0x000001C3F3376510>}
Confusion Matrix:
 [[3131   14]
 [  57  420]]
             precision    recall  f1-score   support

        ham       0.98      1.00      0.99      3145
       spam       0.97      0.88      0.92       477

avg / total       0.98      0.98      0.98      3622

Matthews Correlation Coefficient:  0.9122107742546972


[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed:    3.6s finished


# Multinomial Naive Bayes

In [8]:
prior_0 = sum(y_train == 0) / len(y_train)
prior_1 = sum(y_train == 1) / len(y_train)
# print(prior_0, prior_1)

pipeline_mnb = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB(class_prior=[prior_0, prior_1])),
    #     ('clf', MultinomialNB()),
])

parameters_mnb = {
    'clf__alpha': [1],
    'vect__tokenizer': [ut.scrm114_tokenizer, ut.eager_split_tokenizer],
    'vect__ngram_range': [(1, 1)],
    'vect__max_df': np.logspace(.1, 1, 6),
}

ut.grid_search_analysis(pipeline_mnb, parameters_mnb, *data_args)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
Best score:  0.9138614511424891
Best params:  {'clf__alpha': 1, 'vect__max_df': 1.2589254117941673, 'vect__ngram_range': (1, 1), 'vect__tokenizer': <function scrm114_tokenizer at 0x000001C3F31FE840>}
Confusion Matrix:
 [[3140    5]
 [  44  433]]
             precision    recall  f1-score   support

        ham       0.99      1.00      0.99      3145
       spam       0.99      0.91      0.95       477

avg / total       0.99      0.99      0.99      3622

Matthews Correlation Coefficient:  0.9398405227248262


[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:    2.1s finished


# Random Forests

In [9]:
pipeline_rfc = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', RandomForestClassifier()),
])

parameters_rfc = {
    'vect__tokenizer': [ut.scrm114_tokenizer, ut.eager_split_tokenizer],
    'vect__ngram_range': [(1,1), (1,2), (1,3)],
    'vect__max_df': (.03, .1, .3),
}

ut.grid_search_analysis(pipeline_rfc, parameters_rfc, *data_args)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
Best score:  0.7655684440532785
Best params:  {'vect__max_df': 0.1, 'vect__ngram_range': (1, 1), 'vect__tokenizer': <function scrm114_tokenizer at 0x000001C3F31FE840>}
Confusion Matrix:
 [[3133   12]
 [ 153  324]]
             precision    recall  f1-score   support

        ham       0.95      1.00      0.97      3145
       spam       0.96      0.68      0.80       477

avg / total       0.95      0.95      0.95      3622

Matthews Correlation Coefficient:  0.7873108770282755


[Parallel(n_jobs=1)]: Done  54 out of  54 | elapsed:   11.3s finished
